# Generated by Django 2.0 on 2017-12-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('summarized', models.CharField(blank=True, max_length=50, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.SmallIntegerField(blank=True, default=0)),
                ('meta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doctree.Book')),
                ('parent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doctree.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.SmallIntegerField(blank=True, default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('meta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doctree.Chapter')),
                ('parent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doctree.Knowledge')),
            ],
        ),
    ]
