# Generated by Django 2.0 on 2017-12-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='doctree.Book'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='doctree.Chapter'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='chapter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='doctree.Chapter'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='doctree.Knowledge'),
        ),
    ]
