# Generated by Django 2.0 on 2017-12-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0003_auto_20171207_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctree.Book'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctree.Chapter'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='chapter',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctree.Chapter'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctree.Knowledge'),
        ),
    ]
