# Generated by Django 2.0 on 2017-12-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0005_auto_20171221_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
