# Generated by Django 2.0 on 2017-12-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0006_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctree.Book'),
        ),
    ]
