# Generated by Django 2.0 on 2018-01-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0007_fileupload_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='is_alone',
            field=models.BooleanField(default=False),
        ),
    ]
