# Generated by Django 2.0 on 2018-01-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0010_linkmissing'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
    ]
