# Generated by Django 2.0 on 2018-01-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0011_knowledge_is_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmissing',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='doctree.Knowledge'),
        ),
        migrations.AlterField(
            model_name='linkmissing',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='doctree.Knowledge'),
        ),
    ]
