# Generated by Django 2.0.1 on 2018-02-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0013_auto_20180131_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provision',
            name='law',
        ),
        migrations.RemoveField(
            model_name='provision',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='title',
            name='law',
        ),
        migrations.RemoveField(
            model_name='title',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Law',
        ),
        migrations.DeleteModel(
            name='Provision',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
