# Generated by Django 2.0.1 on 2018-02-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctree', '0014_auto_20180207_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('organization', models.CharField(max_length=32)),
                ('short_name', models.CharField(blank=True, max_length=12, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('modify_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('types', models.CharField(max_length=4)),
                ('serial_number', models.CharField(max_length=12)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctree.Law')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_num', models.IntegerField(blank=True, null=True)),
                ('self_num', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=1)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctree.Law')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctree.Title')),
            ],
        ),
        migrations.AddField(
            model_name='provision',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctree.Title'),
        ),
    ]
